#Data Wrangling: Clean, Transform, Merge, Reshape

In [240]:
import numpy as np
from numpy import nan
import pandas as pd
from pandas import Series, DataFrame

##Combining and Merging Data Sets

###Database-style Data Frame Merges

In [241]:
d1 = DataFrame({'key': list('bacab'), 'data1': range(5)})
d1

data1 key
0      0   b
1      1   a
2      2   c
3      3   a
4      4   b

In [242]:
d2 = DataFrame({'key': list('abd'), 'data2': range(3)})
d2

data2 key
0      0   a
1      1   b
2      2   d

In [243]:
pd.merge(d1, d2)

data1 key  data2
0      0   b      1
1      4   b      1
2      1   a      0
3      3   a      0

In [244]:
pd.merge(d1, d2, on='key')

data1 key  data2
0      0   b      1
1      4   b      1
2      1   a      0
3      3   a      0

In [245]:
d3 = DataFrame({'key1': list('bacab'), 'data1': range(5)})
d4 = DataFrame({'key2': list('abd'), 'data2': range(3)})
pd.merge(d3, d4, left_on='key1', right_on='key2')

data1 key1  data2 key2
0      0    b      1    b
1      4    b      1    b
2      1    a      0    a
3      3    a      0    a

In [246]:
pd.merge(d3, d4, left_on='key1', right_on='key2', how='outer')

data1 key1  data2 key2
0      0    b      1    b
1      4    b      1    b
2      1    a      0    a
3      3    a      0    a
4      2    c    NaN  NaN
5    NaN  NaN      2    d

In [247]:
pd.merge(d3, d4, left_on='key1', right_on='key2', how='left')

data1 key1  data2 key2
0      0    b      1    b
1      1    a      0    a
2      2    c    NaN  NaN
3      3    a      0    a
4      4    b      1    b

In [248]:
pd.merge(d3, d4, left_on='key1', right_on='key2', how='right')

data1 key1  data2 key2
0      0    b      1    b
1      4    b      1    b
2      1    a      0    a
3      3    a      0    a
4    NaN  NaN      2    d

In [249]:
pd.merge(d3, d4, left_on='key1', right_on='key2', how='inner')

data1 key1  data2 key2
0      0    b      1    b
1      4    b      1    b
2      1    a      0    a
3      3    a      0    a

In [250]:
d5 = DataFrame({'key1': list('ffb'), 'key2': list('oto'), 'data1': range(3)})
d6 = DataFrame({'key1': list('ffbb'), 'key2': list('ooto'), 'data2': range(10, 14)})
pd.merge(d5, d6, on=['key1', 'key2'], how='outer')

data1 key1 key2  data2
0      0    f    o     10
1      0    f    o     11
2      1    f    t    NaN
3      2    b    o     13
4    NaN    b    t     12

###Merging on Index

In [251]:
d7 = DataFrame({'key': list('abaabc'), 'value': range(6)})
d7

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [252]:
d8 = DataFrame({'group_val': [3.5, 7]}, index=list('ab'))
d8

group_val
a        3.5
b        7.0

In [253]:
pd.merge(d7, d8, left_on='key', right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

###Concatenating Along an Axis

In [254]:
a1 = np.arange(12).reshape((3, 4))
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [255]:
np.concatenate([a1, a1], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [256]:
s1 = Series([0, 1], index=list('ab'))
s2 = Series([2, 3, 4], index=list('cde'))
s3 = Series([5, 6], index=list('fg'))
pd.concat([s1, s2, s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [257]:
pd.concat([s1, s2, s3], axis=1)

0   1   2
a   0 NaN NaN
b   1 NaN NaN
c NaN   2 NaN
d NaN   3 NaN
e NaN   4 NaN
f NaN NaN   5
g NaN NaN   6

In [258]:
s4 = pd.concat([s1 * 5, s3])
pd.concat([s1, s4], axis=1)

0  1
a   0  0
b   1  5
f NaN  5
g NaN  6

In [259]:
pd.concat([s1, s4], axis=1, join='inner')

0  1
a  0  0
b  1  5

In [260]:
pd.concat([s1, s4], axis=1, join_axes=[list('acbe')])

0   1
a   0   0
c NaN NaN
b   1   5
e NaN NaN

In [261]:
d1 = pd.concat([s1, s1, s3], keys=['one', 'two', 'three'])
d1

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [262]:
d1.unstack()

a   b   f   g
one     0   1 NaN NaN
two     0   1 NaN NaN
three NaN NaN   5   6

In [263]:
pd.concat([d3, d4], axis=1, keys=['level1', 'level2'])

level1      level2     
   data1 key1  data2 key2
0      0    b      0    a
1      1    a      1    b
2      2    c      2    d
3      3    a    NaN  NaN
4      4    b    NaN  NaN

###Combining Data with Overlap

In [264]:
s1 = Series([nan, 2.5, nan, 3.5, 4.5, nan], index=list('fedcba'))
s1

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [265]:
s2 = Series(np.arange(len(s1)), dtype=np.float64, index=list('fedcba'))
s2[-1] = nan
s2

f     0
e     1
d     2
c     3
b     4
a   NaN
dtype: float64

In [266]:
s1.combine_first(s2)

f    0.0
e    2.5
d    2.0
c    3.5
b    4.5
a    NaN
dtype: float64

In [267]:
d1 = DataFrame([[nan, 4.], [5., nan]])
d2 = DataFrame(np.eye(2))
d1.combine_first(d2)

0  1
0  1  4
1  5  1

##Reshaping and Pivoting

In [268]:
d1 = DataFrame(np.arange(6).reshape((2, 3)), index=pd.Index(['Ohio', 'Colorado'], name='state'), columns=pd.Index(['one', 'two', 'three'], name='number'))
d1

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [269]:
result = d1.stack()
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64

In [270]:
result.unstack()

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [271]:
result.unstack(0)

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [272]:
s1 = Series(range(4), index=list('abcd'))
s2 = Series(range(4, 7), index=list('cde'))
d1 = pd.concat([s1, s2], keys=['one', 'two'])
d1.unstack()

a   b  c  d   e
one   0   1  2  3 NaN
two NaN NaN  4  5   6

In [273]:
d1.unstack().stack()

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: float64

In [274]:
d1.unstack().stack(dropna=False)

one  a     0
     b     1
     c     2
     d     3
     e   NaN
two  a   NaN
     b   NaN
     c     4
     d     5
     e     6
dtype: float64

###Pivoting "long" to "wide" Format

In [275]:
d1 = pd.read_csv('data/05/macrodata.csv')
periods = pd.PeriodIndex(year=d1.year, quarter=d1.quarter, name='date')
d1 = DataFrame(d1.to_records(), columns=pd.Index(['realgdp', 'infl', 'unemp'], name='item'), index=periods.to_timestamp('D', 'end'))
ld1 = d1.stack().reset_index().rename(columns={0: 'value'})
ld1[:10]

date     item     value
0 1959-03-31  realgdp  2710.349
1 1959-03-31     infl     0.000
2 1959-03-31    unemp     5.800
3 1959-06-30  realgdp  2778.801
4 1959-06-30     infl     2.340
5 1959-06-30    unemp     5.100
6 1959-09-30  realgdp  2775.488
7 1959-09-30     infl     2.740
8 1959-09-30    unemp     5.300
9 1959-12-31  realgdp  2785.204

In [276]:
pivoted = ld1.pivot('date', 'item', 'value')
pivoted[:10]

item        infl   realgdp  unemp
date                             
1959-03-31  0.00  2710.349    5.8
1959-06-30  2.34  2778.801    5.1
1959-09-30  2.74  2775.488    5.3
1959-12-31  0.27  2785.204    5.6
1960-03-31  2.31  2847.699    5.2
1960-06-30  0.14  2834.390    5.2
1960-09-30  2.70  2839.022    5.6
1960-12-31  1.21  2802.616    6.3
1961-03-31 -0.40  2819.264    6.8
1961-06-30  1.47  2872.005    7.0

In [277]:
ld1['value2'] = np.random.randn(len(ld1))
ld1[:10]

date     item     value    value2
0 1959-03-31  realgdp  2710.349  0.108999
1 1959-03-31     infl     0.000  1.460510
2 1959-03-31    unemp     5.800 -1.610997
3 1959-06-30  realgdp  2778.801 -0.828095
4 1959-06-30     infl     2.340  0.000094
5 1959-06-30    unemp     5.100  1.215614
6 1959-09-30  realgdp  2775.488 -0.500687
7 1959-09-30     infl     2.740  0.039847
8 1959-09-30    unemp     5.300 -0.201910
9 1959-12-31  realgdp  2785.204 -0.933236

In [278]:
pivoted = ld1.pivot('date', 'item')
pivoted[:10]

value                    value2                    
item        infl   realgdp unemp      infl   realgdp     unemp
date                                                          
1959-03-31  0.00  2710.349   5.8  1.460510  0.108999 -1.610997
1959-06-30  2.34  2778.801   5.1  0.000094 -0.828095  1.215614
1959-09-30  2.74  2775.488   5.3  0.039847 -0.500687 -0.201910
1959-12-31  0.27  2785.204   5.6 -0.158369 -0.933236  0.343744
1960-03-31  2.31  2847.699   5.2 -0.622239 -1.872643 -0.514695
1960-06-30  0.14  2834.390   5.2  1.964625 -0.505181  0.327802
1960-09-30  2.70  2839.022   5.6 -0.493773 -0.622720  0.204958
1960-12-31  1.21  2802.616   6.3  1.062783  0.446293  0.537562
1961-03-31 -0.40  2819.264   6.8 -0.042969  0.912912  0.617269
1961-06-30  1.47  2872.005   7.0 -1.558461 -0.181354  0.910167

In [279]:
unstacked = ld1.set_index(['date', 'item']).unstack('item')
unstacked[:10]

value                    value2                    
item        infl   realgdp unemp      infl   realgdp     unemp
date                                                          
1959-03-31  0.00  2710.349   5.8  1.460510  0.108999 -1.610997
1959-06-30  2.34  2778.801   5.1  0.000094 -0.828095  1.215614
1959-09-30  2.74  2775.488   5.3  0.039847 -0.500687 -0.201910
1959-12-31  0.27  2785.204   5.6 -0.158369 -0.933236  0.343744
1960-03-31  2.31  2847.699   5.2 -0.622239 -1.872643 -0.514695
1960-06-30  0.14  2834.390   5.2  1.964625 -0.505181  0.327802
1960-09-30  2.70  2839.022   5.6 -0.493773 -0.622720  0.204958
1960-12-31  1.21  2802.616   6.3  1.062783  0.446293  0.537562
1961-03-31 -0.40  2819.264   6.8 -0.042969  0.912912  0.617269
1961-06-30  1.47  2872.005   7.0 -1.558461 -0.181354  0.910167

##Data Transformation

###Removing Duplicates

In [280]:
d1 = DataFrame({'k1': ['one'] * 3 + ['two'] * 4, 'k2': [1, 1, 2, 3, 3, 4, 4]})
d1

k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

In [281]:
d1.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [282]:
d1.drop_duplicates()

k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

In [283]:
d1.drop_duplicates(['k1'])

k1  k2
0  one   1
3  two   3

In [284]:
d1.drop_duplicates(['k1', 'k2'], take_last=True)

k1  k2
1  one   1
2  one   2
4  two   3
6  two   4

###Transforming Data Using a Function or Mapping

In [285]:
d1 = DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami', 'corned beef', 'Bacon', 'pastrami', 'honey ham', 'nova lox'], 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
d1

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [286]:
meat_to_animal = {
    'bacon': 'pig',
    'pulled pork': 'pig',
    'pastrami': 'cow',
    'corned beef': 'cow',
    'honey ham': 'pig',
    'nova lox': 'salmon'
}
d1['animal'] = d1['food'].map(str.lower).map(meat_to_animal)
d1

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [287]:
d1['animal2'] = d1['food'].map(lambda x: meat_to_animal[x.lower()])
d1

food  ounces  animal animal2
0        bacon     4.0     pig     pig
1  pulled pork     3.0     pig     pig
2        bacon    12.0     pig     pig
3     Pastrami     6.0     cow     cow
4  corned beef     7.5     cow     cow
5        Bacon     8.0     pig     pig
6     pastrami     3.0     cow     cow
7    honey ham     5.0     pig     pig
8     nova lox     6.0  salmon  salmon

###Replacing Values

In [288]:
s1 = Series([1., -999., 2., -999., -1000., 3.])
s1

0       1
1    -999
2       2
3    -999
4   -1000
5       3
dtype: float64

In [289]:
s1.replace(-999., nan)

0       1
1     NaN
2       2
3     NaN
4   -1000
5       3
dtype: float64

In [290]:
s1.replace([-999., -1000.], nan)

0     1
1   NaN
2     2
3   NaN
4   NaN
5     3
dtype: float64

In [291]:
s1.replace([-999., -1000.], [nan, 0])

0     1
1   NaN
2     2
3   NaN
4     0
5     3
dtype: float64

In [292]:
s1.replace({-999.: nan, -1000.: 0})

0     1
1   NaN
2     2
3   NaN
4     0
5     3
dtype: float64

###Renaming Axis Indexes

In [293]:
d1 = DataFrame(np.arange(9).reshape((3, 3)), columns=['foo', 'bar', 'baz'])
d1

foo  bar  baz
0    0    1    2
1    3    4    5
2    6    7    8

In [294]:
d1.columns = d1.columns.map(str.upper)
d1

FOO  BAR  BAZ
0    0    1    2
1    3    4    5
2    6    7    8

###Discretization and Binning

In [295]:
s = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
cats = pd.cut(s, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, object): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [296]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [297]:
cats.categories

Index([u'(18, 25]', u'(25, 35]', u'(35, 60]', u'(60, 100]'], dtype='object')

In [298]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [299]:
s = np.random.randn(1000)
pd.cut(s, 3, precision=2)

[(-1, 1.012], (-1, 1.012], (-1, 1.012], (-1, 1.012], (1.012, 3.022], ..., (-1, 1.012], (-1, 1.012], (-1, 1.012], (1.012, 3.022], (-1, 1.012]]
Length: 1000
Categories (3, object): [(-3.013, -1] < (-1, 1.012] < (1.012, 3.022]]

In [300]:
pd.qcut(s, 4)

[(-0.0501, 0.684], [-3.00699, -0.735], (-0.735, -0.0501], (-0.0501, 0.684], (0.684, 3.0221], ..., (-0.0501, 0.684], [-3.00699, -0.735], [-3.00699, -0.735], (0.684, 3.0221], (-0.735, -0.0501]]
Length: 1000
Categories (4, object): [[-3.00699, -0.735] < (-0.735, -0.0501] < (-0.0501, 0.684] < (0.684, 3.0221]]

In [301]:
pd.qcut(s, [0.0, 0.1, 0.5, 0.9, 1])

[(-0.0501, 1.392], (-1.289, -0.0501], (-1.289, -0.0501], (-0.0501, 1.392], (1.392, 3.0221], ..., (-0.0501, 1.392], (-1.289, -0.0501], (-1.289, -0.0501], (1.392, 3.0221], (-1.289, -0.0501]]
Length: 1000
Categories (4, object): [[-3.00699, -1.289] < (-1.289, -0.0501] < (-0.0501, 1.392] < (1.392, 3.0221]]